# Generated by Django 4.2.7 on 2025-09-23 23:56

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='APIUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endpoint', models.CharField(max_length=100, verbose_name='Endpoint')),
                ('method', models.CharField(max_length=10, verbose_name='Método HTTP')),
                ('ip_address', models.GenericIPAddressField(verbose_name='Dirección IP')),
                ('user_agent', models.TextField(blank=True, null=True, verbose_name='User Agent')),
                ('response_status', models.IntegerField(verbose_name='Estado de respuesta')),
                ('response_time', models.FloatField(verbose_name='Tiempo de respuesta (ms)')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Timestamp')),
            ],
            options={
                'verbose_name': 'Uso de API',
                'verbose_name_plural': 'Uso de API',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='ModelInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(max_length=100, verbose_name='Nombre del modelo')),
                ('version', models.CharField(max_length=20, verbose_name='Versión')),
                ('accuracy', models.FloatField(verbose_name='Precisión')),
                ('f1_score', models.FloatField(verbose_name='F1-Score')),
                ('training_date', models.DateTimeField(verbose_name='Fecha de entrenamiento')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
            ],
            options={
                'verbose_name': 'Información del Modelo',
                'verbose_name_plural': 'Información de Modelos',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NewsAnalysis',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('text', models.TextField(help_text='Texto completo de la noticia a analizar', verbose_name='Texto de la noticia')),
                ('prediction', models.CharField(choices=[('VERDADERA', 'Noticia Verdadera'), ('FALSA', 'Noticia Falsa')], max_length=10, verbose_name='Predicción')),
                ('confidence', models.FloatField(help_text='Nivel de confianza de la predicción (0.0 - 1.0)', verbose_name='Confianza')),
                ('probability_fake', models.FloatField(help_text='Probabilidad de que la noticia sea falsa', verbose_name='Probabilidad de ser falsa')),
                ('probability_real', models.FloatField(help_text='Probabilidad de que la noticia sea verdadera', verbose_name='Probabilidad de ser verdadera')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='Dirección IP')),
                ('user_agent', models.TextField(blank=True, null=True, verbose_name='User Agent')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
            ],
            options={
                'verbose_name': 'Análisis de Noticia',
                'verbose_name_plural': 'Análisis de Noticias',
                'ordering': ['-created_at'],
            },
        ),
    ]
